---
- hosts: all
  tasks:
    - name: Change git branches for LMS code and all plugins on DVM
      become: yes
      become_user: root
      become_method: sudo
      shell: | 
        sudo wget -O /home/awx/change_git_branch.sh https://raw.githubusercontent.com/jstilwell/lp-na-ansible-playbooks/main/scripts/change_git_branch.sh
        sudo chmod +x /home/awx/change_git_branch.sh
        sudo /home/awx/change_git_branch.sh {{ lms_code_directory }} {{ git_branch }} {{ git_password }}
      no_log: true
      register: cmd_output

    - name: "Print the command output to a console"
      debug:
        msg: "{{ cmd_output.stdout }}"