---
- hosts: all
  tasks:    
    - name: Get sudoers file content
      become: yes
      become_user: root
      become_method: sudo
      shell: | 
        cat /etc/sudoers
      register: file_content

    - name: "Print the file content to a console"
      debug:
        msg: "{{ file_content.stdout }}"

    - name: "Save the file content to a '$resolve_conf' variable"
      set_fact:
      resolve_conf: "{{ file_content.stdout }}"

    - name: "Print the '$resolve_conf' variable"
      debug:
        msg: "{{ resolve_conf }}"